language: php

php:
  - '7.2'
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - ILLUMINATE_VERSION=5.5.* TESTBENCH_VERSION=3.5.*
    - ILLUMINATE_VERSION=5.6.* TESTBENCH_VERSION=3.6.*
    - ILLUMINATE_VERSION=5.7.* TESTBENCH_VERSION=3.7.*
    - ILLUMINATE_VERSION=5.8.* TESTBENCH_VERSION=3.8.*
    - ILLUMINATE_VERSION=6.0.* TESTBENCH_VERSION=4.0.*

before_install:
  - composer require illuminate/broadcasting:${ILLUMINATE_VERSION} illuminate/support:${ILLUMINATE_VERSION} --no-update
  - composer require orchestra/testbench:${TESTBENCH_VERSION} --no-update

install:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
